const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_MODEL = 'gemini-2.0-flash-exp';
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

interface GeminiPart {
  text?: string;
  inlineData?: { mimeType: string; data: string };
}

interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
        inlineData?: { mimeType: string; data: string };
      }>;
    };
  }>;
}

export async function generateImage(
  prompt: string,
  referenceImages?: Buffer[]
): Promise<{ imageBase64: string; mimeType: string; text?: string }> {
  if (!GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY is not set');
  }

  const parts: GeminiPart[] = [];

  // Add reference images first
  if (referenceImages && referenceImages.length > 0) {
    for (const buf of referenceImages) {
      parts.push({
        inlineData: {
          mimeType: 'image/png',
          data: buf.toString('base64'),
        },
      });
    }
  }

  // Add prompt text
  parts.push({ text: prompt });

  const body = {
    contents: [{ parts }],
    generationConfig: {
      responseModalities: ['TEXT', 'IMAGE'],
    },
  };

  const res = await fetch(`${GEMINI_URL}?key=${GEMINI_API_KEY}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Gemini API error ${res.status}: ${errText}`);
  }

  const data: GeminiResponse = await res.json();
  const responseParts = data.candidates?.[0]?.content?.parts;
  if (!responseParts) {
    throw new Error('No response parts from Gemini');
  }

  let imageBase64 = '';
  let mimeType = 'image/png';
  let text = '';

  for (const part of responseParts) {
    if (part.inlineData) {
      imageBase64 = part.inlineData.data;
      mimeType = part.inlineData.mimeType;
    }
    if (part.text) {
      text += part.text;
    }
  }

  if (!imageBase64) {
    throw new Error('No image generated by Gemini. Response text: ' + text);
  }

  return { imageBase64, mimeType, text: text || undefined };
}
